# NNIA Assignment 0

**DEADLINE: 10.11.2021 0800 CET**

- Trevor Atkins & trat00001 (Teams username: trat00001@uni-saarland.de): 
- Tsimafei Prakapenka & tspr00001 (Teams username: tspr00001@uni-saarland.de):
- Hours of work per person: Tsimafei: 1.5h Trevor: 45min

# Submission Instructions

**IMPORTANT** Please make sure you read the following instructions carefully. If you are unclear about any part of the assignment, ask questions **before** the assignment deadline. All course-related questions can be addressed on the course **[Piazza Platform](https://piazza.com/class/kvc3vzhsvh55rt)**

* Assignments are to be submitted in a **team of 2**.
* Please include your **names**, **ID's**, **Teams usernames**, and **approximate total time spent per person** at the beginning of the Notebook in the space provided
* Make sure you appropriately comment your code wherever required. 
* Your final submission should contain this completed Jupyter Notebook, including the bonus question (if you attempt it), and any necessary Python files.
* Do **not** submit any data or cache files (e.g. `__pycache__`).
* Upload the **zipped** folder (*.zip* is the only accepted extension) in **Teams**.
* Only **one member** of the group should make the submisssion.
* **Important** please name the submitted zip folder as: `Name1_id1_Name2_id2.zip`. The Jupyter Notebook should also be named: `Name1_id1_Name2_id2.ipynb`. This is **very important** for our internal organization repeatedly students fail to do this.

<font color="red">Failure to follow the above instructions will result in point penalties at the discretion of the instructors.</font>

This zeroth assignment is special in that you will not receive any points from it (nor will you have points deduced).
We will nevertheless provide feedback to help you with your later submissions.

# Exercise 1: Course Organization and Resources (0 points)

Course orientation and assignment instructions. Please carefully orient yourself with the course organizational sites (Teams Channels and Piazza) and the instructions on how to use Jupyter Notebooks and how to hand in the assignments.


## 1.1 Course Organization Resources

* If I have questions about the assignments, grading, etc. and need to get in touch with the tutor(s), how should I do that?
* I have a few questions about the course contents... Where should I ask them? 







## 1.2 Assignment Submission Instructions




*   Where and how assignements are to be submitted? 
*   What should and should not be included in your submission?



## <font color="green"> 1.1 DONE </font>
Questions about the assignments, grading, etc. and to get in touch with the tutor(s) can be asked through Microsoft Teams or e-mail. 
Questions about course content can be asked on the Piazza forum, with a label as to whether it is for NNTI or NNIA.
## <font color="green">1.2 DONE</font>
Assignments are to be submitted on Microsoft Teams according to the instructions provided. What should be included in the submission are: Names, ID, Team usernames, approximate time spent per person, all the files as a zipped folder with Name, ID as the file names. What should not be included are data and cache files and not more than one member submitting. 


## 1.3 Using Jupyter Notebooks

Since all assignments unless otherwise instructed are to be submitted via Jupyter Notebooks, please familiarize yourself with how to use them by reading the **"Instructions for using Jupyter Notebooks and Assignments"** PDF file provided in the assignment folder.
If you feel that you already know all this, you can skip reading it at your own risk.

Below are some additional links to a few resources on how to use Jupyter Notebooks you may find useful:

* [DataCamp Jupyter Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Markdown Formatting Cheatsheet](https://www.markdownguide.org/basic-syntax/)
* [How to import Python modules to Jupyter Notebook](https://youtu.be/BW_8UAnO9Og)

After consulting the above resources (and/or elsewhere if you prefer), please perform the following:
1.   Write a Python script containing *a function* that prints a message to the standard output. e.g. a simple function printing "Hello World!" is acceptable.
2.   Import this function to the cell in this notebook below
3.   Execute the cell to verify that you have successfully done so. You should see the message written in the function in the .py file you have imported in the notebook.



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# TODO
# import your function from your .py file here and run this cell when you're done!
import sys
sys.path.append('/content/drive/MyDrive/Neural Networks/assignment0_rev1')
from importlib import reload
import assign0_func1
assign0_func1 = reload(assign0_func1)
assign0_func1.printHelloWorld()

Hello World


# Exercise 2: Linear Algebra Basics (0 points)


## 2.1

- Multiply the following matrices.
- What conclusion can you infer about commutativity of matrix multiplication?

$$
X = \begin{pmatrix}
1 & 2 \\
3 & 4 
\end{pmatrix}
\times 
\begin{pmatrix}
-1 & 5 \\
4 & 0 
\end{pmatrix}
$$

$$
Y =
\begin{pmatrix}
-1 & 5 \\
4 & 0 
\end{pmatrix}
\times 
\begin{pmatrix}
1 & 2 \\
3 & 4 
\end{pmatrix}
$$

## 2.2

- What is a transpose of a matrix?

- What is an identity matrix?

- What is a symmetric matrix?

- What is a matrix inverse?


## 2.3

- Find the inverse of the following matricies:

$$
A =
\begin{pmatrix}
1 & 2 \\
3 & 4 
\end{pmatrix}
\qquad
B =
\begin{pmatrix}
1 & 2 \\
2 & 4  
\end{pmatrix}
\qquad
C =
\begin{pmatrix}
1 & 2 & 0 \\
3 & 4 & 1 
\end{pmatrix}
$$


## <font color="green">2.1 DONE</font>
Matrix multiplication is an apparently non-commucative operation.
$$
X = \begin{pmatrix}
7 & 5 \\
13 & 15 
\end{pmatrix}
$$

$$
Y =
\begin{pmatrix}
14 & 18 \\
4 & 8 
\end{pmatrix}
$$




## <font color="green">2.2 DONE</font>

- A transpose of a matrix switches the row and column indices of the matrix.

- An identity matrix is when a matrix of size *n* is a *nxn* square matrix where the main diagonal of the matrix has ones and zeroes everywhere else. 

- A symmetric matrix is a square matrix that is equal to its transpose.

- A matrix inverse is a matrix such that if it is multiplied with the original matrix, the product is the identity matrix.


## <font color="green">2.3 DONE</font>
It is impossible to invert non-square matrices and matrices with a zero determiner. Then, matrices B ($det(B) = 1*4 - 2*2 = 0$) and C (non-square) are not invertible. Let's find the inverse of A with a non-zero determiner ($det(A) = 1*4 - 2*3 = -2$).



$$A ^{-1} = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix} ^ {-1} =  \begin{pmatrix}
a & b \\
c & d 
\end{pmatrix} ^{-1} = \frac{1}{det(A)} * \begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix} = \frac{1} {-2} * \begin{pmatrix}
4 & -2 \\
-3 & 1 
\end{pmatrix} = \begin{pmatrix}
2 & -1 \\
-1.5 & 0.5 
\end{pmatrix}$$


# Exercise 3: Working with Numpy (0 points)

You may be wondering why skip the second exercise and not simply use the results you find with Numpy.
The exercises are meant mostly for you to help you prepare for the exam where you can expect exercises similar to the second one.
Programming exercises should help you become better practicioners of learned material.

## 3.1

Use Numpy to:
- Find the dot product $X$ and $Y$
- Find the sum of $X$ and $(-6 \cdot Y)$
- Find the inverses of matricies $A$, $B$ and $C$.
- Show the difference between the dot product of $X$ and $Y$ and the elementwise product (Hadamard product) of $X \odot Y$

## 3.2

With Numpy:
- Generate two rectangular random matricies $K$ and $L$ of shape such that they are multiplicable with $L \times K$
- Validate that $(K^T \times L^T)^T = L \times K$

## <font color="green">3.1 DONE</font>


In [ ]:
import numpy as np
import torch # just to check mm in torch vs numpy

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[-1, 5], [4, 0]])

In [ ]:
# this matmul will work even with ordinary python 2d lists, 
# but I converted it to ndarrays to check other options for matrix multiplications
x = np.matmul(m1, m2)
x

array([[ 7,  5],
       [13, 15]])

In [ ]:
m1 @ m2

array([[ 7,  5],
       [13, 15]])

In [ ]:
torch.mm(torch.from_numpy(m1), torch.from_numpy(m2))

tensor([[ 7,  5],
        [13, 15]])

In [ ]:
y = np.matmul(m2, m1)
y

array([[14, 18],
       [ 4,  8]])

- find the dot product $X$ and $Y$

In [ ]:
np.dot(x, y)

array([[118, 166],
       [242, 354]])

In [ ]:
np.dot(y, x)

array([[332, 340],
       [132, 140]])

In [ ]:
v1 = [1, 2, 3]
v2 = [11, 12, 13]

print(np.dot(v1, v2))
print(np.dot(v2, v1))

74
74


- find the sum of $X$ and $(-6 \cdot Y)$

In [ ]:
x + y*(-6)

array([[ -77, -103],
       [ -11,  -33]])

- find the inverses of matricies $A$, $B$ and $C$.

$$
A =
\begin{pmatrix}
1 & 2 \\
3 & 4 
\end{pmatrix}
\qquad
B =
\begin{pmatrix}
1 & 2 \\
2 & 4  
\end{pmatrix}
\qquad
C =
\begin{pmatrix}
1 & 2 & 0 \\
3 & 4 & 1 
\end{pmatrix}
$$

In [ ]:
A = [[1, 2], [3, 4]]
B = [[1, 2], [2, 4]]
C = [[1, 2, 0], [3, 4, 1]]

In [ ]:
# B and C matrices are non-invertible (explained in task 2).
print("A inverse: \n", np.linalg.inv(A))

A inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


- Show the difference between the dot product of $X$ and $Y$ and the elementwise product (Hadamard product) of $X \odot Y$

In [ ]:
# Hadamard product is commutative operation, whereas dot product is not.
print('Hadamard product of X and Y:\n', x * y)
print('Hadamard product of Y and X:\n', y * x)
print('Dot product of X and Y:\n', np.dot(x, y))
print('Dot product of Y and X:\n', np.dot(y, x))

Hadamard product of X and Y:
 [[ 98  90]
 [ 52 120]]
Hadamard product of Y and X:
 [[ 98  90]
 [ 52 120]]
Dot product of X and Y:
 [[118 166]
 [242 354]]
Dot product of Y and X:
 [[332 340]
 [132 140]]


## <font color="green">3.2 DONE</font>

- generate two rectangular random matricies $K$ and $L$ of shape such that they are multiplicable with $L \times K$
- validate that $(K^T \times L^T)^T = L \times K$


In [ ]:
n = 7
m = 5
q = 3

In [ ]:
L = np.random.rand(n, m)
K = np.random.rand(m, q)

print("L matrix: \n", L)
print("K matrix: \n", K)

L matrix: 
 [[0.01518385 0.27625822 0.04523711 0.07448166 0.79076523]
 [0.04636351 0.11973256 0.37486421 0.18739813 0.19969758]
 [0.16173536 0.820347   0.23188437 0.73140621 0.22857341]
 [0.91473459 0.40587186 0.33735231 0.99305241 0.43541645]
 [0.18922376 0.81452074 0.98174972 0.18008688 0.05833631]
 [0.34347099 0.71527745 0.93418182 0.83794465 0.54412458]
 [0.04864881 0.61945753 0.39935141 0.39396894 0.17117286]]
K matrix: 
 [[0.9187775  0.20441508 0.29963352]
 [0.70485767 0.16354991 0.21663839]
 [0.49086761 0.15272914 0.85492659]
 [0.50812896 0.7730483  0.16016774]
 [0.39934387 0.30284142 0.69500844]]


In [ ]:
right_res = L @ K
print(right_res, type(right_res))

[[0.58451227 0.35224923 0.6645902 ]
 [0.48597128 0.29165684 0.52911875]
 [1.30357928 0.83727815 0.70043223]
 [1.97059435 1.20442899 1.1120971 ]
 [1.34468847 0.47871928 1.14186651]
 [1.92137858 1.14242615 1.56891173]
 [0.94589935 0.52864463 0.67225893]] <class 'numpy.ndarray'>


In [ ]:
L_t = np.transpose(L)
K_t = np.transpose(K)

left_res = np.transpose(K_t @ L_t)

print(left_res, type(left_res))

[[0.58451227 0.35224923 0.6645902 ]
 [0.48597128 0.29165684 0.52911875]
 [1.30357928 0.83727815 0.70043223]
 [1.97059435 1.20442899 1.1120971 ]
 [1.34468847 0.47871928 1.14186651]
 [1.92137858 1.14242615 1.56891173]
 [0.94589935 0.52864463 0.67225893]] <class 'numpy.ndarray'>


In [ ]:
assert (left_res == right_res).all() == True

# Exercise 4 (0 points)

We also provide you with the zeroth exercise for the CS track.
You are of course not required to work through that sheet but we advise you to do so (despite the investment in time and energy) because of the following points:
- it is very well made and interactive "read-only"
- it clearly shows the standard which we expect you to have in your assignments and therefore having this knowledge will increase your chances of better grades on your assignments
- it will make you a better programmer in data/scientific Python which is a highly marketable skill

# Bonus (0 points)

**Network Design Intuition**

One day, a friend of yours buys a bag of iris flower seeds, and plants them. There are supposed to be three different species of flowers included, but your friend doesn’t know how to identify them, and after the flowers bloom they come to you for help. Fortunately, you have access to a set of data on a large number of flowers of these species. Each flower has its species listed, and includes four measurements for each flower: its sepal length, sepal width, petal length, and petal width. Eager to put your new skills to use, you figure you can use machine learning to help your friend identify which of the three species each of their plants are.



1.   Would this problem involve supervised learning or unsupervised learning? Why?
2.   Could we design a neural network to solve this problem? If not, why not? If so, give a basic description of the network’s properties, such as the size and type of the input and output, along with a brief justification of your choices. (If you use outside sources, please cite accordingly.)



## <font color="green">Bonus Answer: DONE</font>







1. This is definitely supervised learning, since we have target labels in training data ('Each flower has its species listed').
2. We could definitely design a neural network to solve this task. The setup is similar to a lot of problems for NNs: we have training data with labels and features ('Each flower has its species listed, and includes four measurements for each flower: its sepal length, sepal width, petal length, and petal width.') and the goal of inference is to predict target label given input features ('sepal length, sepal width, petal length, and petal width'). Input size is 4, since we have 4 features in training data. Output size is 3 because we are choosing between 3 target labels ('three different species of flowers included'). I expect the resulting vector to be a probability vector of each label, and the answer is the biggest probability amongst vector elements.

I am sure that actual coding is not required. However, I am attending 'ML in Cybersecurity', and we had today the same example about Fisher's Iris dataset. Wanted to add it here for the full picture and to deepen my understanding.

In [53]:
import random

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [57]:
import torch
import torch.nn as nn
import torch.optim as optim

In [54]:
# Fix seeds for random number generators
seed = 1001
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)

In [55]:
iris_data = load_iris()
X = iris_data['data']
y = iris_data['target']

# Standardize features to mean 0 var 1
scalar = StandardScaler()
X = scalar.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=seed)

print(f"Shape of training features: {X_train.shape}")
print(f"Shape of validation features: {X_val.shape}")
print(f"Shape of testing features: {X_test.shape}")
print(f"Shape of testing labels: {y_test.shape}")

num_features = X.shape[1]
num_labels = np.max(y) + 1

print(f"Number of features: {num_features}")
print(f"Number of labels: {num_labels}")

# Wrap it in a PyTorch data loader
def wrap_data(X, y):
  dataset = torch.utils.data.TensorDataset(torch.from_numpy(X).float(), torch.from_numpy(y))
  return torch.utils.data.DataLoader(dataset=dataset, batch_size=16, shuffle=True)

train_loader = wrap_data(X_train, y_train)
val_loader = wrap_data(X_val, y_val)
test_loader = wrap_data(X_test, y_test)

Shape of training features: (96, 4)
Shape of validation features: (24, 4)
Shape of testing features: (30, 4)
Shape of testing labels: (30,)
Number of features: 4
Number of labels: 3


In [58]:
# Simple fully connected feed-forward network. 
# Hidden parameters were chosen almost randomly and, actually, it is a subject to research for more complicated tasks.
class FullyConnected(nn.Module):

  def __init__(self):
    super(FullyConnected, self).__init__()
    self.layers = nn.Sequential(
        nn.Linear(in_features=num_features, out_features=50),
        nn.ReLU(),

        nn.Linear(in_features=50, out_features=25),
        nn.ReLU(),

        nn.Linear(in_features=25, out_features=num_labels),
    )

  def forward(self, x):
    return self.layers(x)

In [74]:
model = FullyConnected()
optimizer = optim.Adam(model.parameters(), lr=0.0002)
loss_function = nn.CrossEntropyLoss()

print(model)

FullyConnected(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=50, bias=True)
    (1): ReLU()
    (2): Linear(in_features=50, out_features=25, bias=True)
    (3): ReLU()
    (4): Linear(in_features=25, out_features=3, bias=True)
  )
)


In [75]:
EPOCHS = 300

for epoch in range(EPOCHS):
  model.train() # puts model into training mode
  for (X_batch, y_batch) in train_loader:

    prediction = model(X_batch)
    loss = loss_function(prediction, y_batch)

    # we are calling zero_grad to calculate backprop only for current step discarding previous values
    # https://stackoverflow.com/questions/48001598/why-do-we-need-to-call-zero-grad-in-pytorch
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if epoch % 10 == 9:
    # we do not want to compute gradients during inference
    # https://pytorch.org/docs/stable/generated/torch.no_grad.html
    with torch.no_grad():
      model.eval()
      predictions = model(torch.from_numpy(X_val).float())
      accuracy = (torch.argmax(predictions, -1) == torch.from_numpy(y_val)).float().mean()
      print(f"Validation Accuracy: {accuracy}")

Validation Accuracy: 0.875
Validation Accuracy: 0.7916666865348816
Validation Accuracy: 0.7916666865348816
Validation Accuracy: 0.7916666865348816
Validation Accuracy: 0.8333333134651184
Validation Accuracy: 0.8333333134651184
Validation Accuracy: 0.875
Validation Accuracy: 0.875
Validation Accuracy: 0.875
Validation Accuracy: 0.9166666865348816
Validation Accuracy: 0.9166666865348816
Validation Accuracy: 0.9166666865348816
Validation Accuracy: 0.9166666865348816
Validation Accuracy: 0.9166666865348816
Validation Accuracy: 0.9583333134651184
Validation Accuracy: 0.9583333134651184
Validation Accuracy: 0.9583333134651184
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0
Validation Accuracy: 1.0


In [76]:
model.eval()

with torch.no_grad():
  model.eval()
  predictions = model(torch.from_numpy(X_test).float())
  accuracy = (torch.argmax(predictions, -1) == torch.from_numpy(y_test)).float().mean()
  print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.9666666388511658
